### PR TITLE
attempt to update to 2.5.0

### PR DESCRIPTION
**Pull request by epaule**
* I changed the releases to 2.5.0 and the dependencies to 1.4
* in addition i left the .git files in the image so the viewers git plugin does work

### CODE REVIEW

**Comment by rjchallis** [comment]
Thanks for sharing this. I'll have to leave these unmerged as I'm trying to streamline the dependencies a little so I'm rebuilding in a single image with both dependencies and btk. I'll commit to a develop branch once I'm done so you can check it out. Hopefully won't need any more changes to get it working but happy to receive prs against the new version if spot anything.

Meanwhile here's the list of dependencies that I'm including in case it helps you get up and running sooner:

```
name: btk_env
channels:
  - conda-forge
  - bioconda
  - tolkit
  - r
  - defaults
dependencies:
  - busco==5.1.2
  - defusedxml==0.7.1
  - diamond==2.0.8
  - docopt==0.6.2
  - geckodriver==0.29.0
  - minimap2==2.17
  - mosdepth==0.2.9
  - nodejs==10.13.0
  - pip==21.0.1
  - psutil==5.8.0
  - pysam==0.16.0.1
  - python==3.8.8
  - pyvirtualdisplay==2.1
  - pyyaml==5.4.1
  - samtools==1.10
  - selenium==3.141.0
  - seqtk==1.3
  - snakemake==6.0.5
  - tolkein==0.2.6
  - tqdm==4.59.0
  - ujson==4.0.2
  - urllib3==1.26.3
  - pip:
    - fastjsonschema==2.15.0
```

**Comment by rjchallis** [comment]
That's the new Dockerfile in the develop branch (untested, but should be a better point to work from) I've also set it uploading to docker hub in case it works so the pre-built image will be at genomehubs/blobtoolkit:2.5.0 once the upload is complete (still an 8GB image so the upload may take a while yet).

**Comment by epaule** [comment]
thanks @rjchallis :-)
there is actually another thing that causes issues to build the image: the step with the tolkein tool uses the system python and the redefinition of the PYTHONLIB seems not to let it pick up the 2.7 modules (but pip finds it).

**Comment by epaule** [comment]
should we close the pull request, as you are now way ahead?

**Pull request closed without merging**
